services:
  app:
    build:
      context: .
    ports:
      - "${APP_PORT}:8080"
  database:
    image: postgres:15.4
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crm
volumes:
  postgresql:
